# Bot Configuration
bot:
  token: "${BOT_TOKEN}"
  prefix: "!"
  status: "Watching for flips"
  activity_type: "watching"

# Access Control
access:
  owner_id: "${OWNER_ID}"
  admin_ids: []
  blacklisted_users: []
  whitelist_enabled: false
  whitelisted_users: []

# Channel Configuration
channels:
  notifications:
    flip_alerts: ""
    announcements: ""
    logs: ""
    status: ""
  admin:
    commands: ""
    logs: ""

# Button Customization
buttons:
  verify_label: "Verify"
  qa_label: "Q&A"
  verify_emoji: "✅"
  qa_emoji: "❓"
  verify_style: "green"
  qa_style: "blurple"

# API Keys
api:
  hypixel: "${HYPIXEL_API_KEY}"
  microsoft:
    client_id: "${MS_CLIENT_ID}"
    client_secret: "${MS_CLIENT_SECRET}"
    redirect_url: "http://localhost:8000/callback"

# Webhook URLs
webhooks:
  admin: "${ADMIN_WEBHOOK}"
  notifications: "${NOTIFICATIONS_WEBHOOK}"

# Flip Detection Settings
flip_settings:
  check_interval: 30
  min_profit: 100000
  min_profit_percentage: 20
  max_price: 1000000000
  blacklisted_items: []
  whitelist_items: []

# Embed Settings
embeds:
  colors:
    success: 0x00ff00
    error: 0xff0000
    info: 0x0000ff
    flip: 0xffa500
  show_timestamps: true
  show_footers: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "bot.log"

# Security Settings
security:
  encryption_key: "${ENCRYPTION_KEY}"
  max_login_attempts: 3
  session_timeout: 3600
  require_2fa: true 