# Bot Configuration
bot:
  token: "your_bot_token_here"  # Discord bot token
  prefix: "!"  # Default prefix for legacy commands
  status: "Watching for flips"  # Bot's status message
  activity_type: "watching"  # playing, watching, listening, competing

# Access Control
access:
  owner_id: "your_discord_id_here"  # Bot owner's Discord ID
  admin_ids:  # List of admin Discord IDs
    - "admin1_id_here"
    - "admin2_id_here"
  blacklisted_users: []  # Users who can't use the bot
  whitelist_enabled: false  # If true, only whitelisted users can use the bot
  whitelisted_users: []  # Users who can use the bot when whitelist is enabled

# Channel Configuration
channels:
  notifications:
    flip_alerts: "channel_id_here"  # Channel for flip notifications
    announcements: "channel_id_here"  # Channel for bot announcements
    logs: "channel_id_here"  # Channel for logging bot actions
    status: "channel_id_here"  # Channel for status updates
  admin:
    commands: "channel_id_here"  # Channel for admin commands
    logs: "channel_id_here"  # Channel for admin logs

# Button Customization
buttons:
  verify_label: "Verify"  # Custom label for verify button
  qa_label: "Q&A"  # Custom label for Q&A button
  verify_emoji: "✅"  # Custom emoji for verify button
  qa_emoji: "❓"  # Custom emoji for Q&A button
  verify_style: "green"  # Button style: green, blue, red, grey
  qa_style: "blurple"  # Button style: green, blue, red, grey

# API Keys
api:
  hypixel: "your_hypixel_api_key_here"
  microsoft:
    client_id: "your_microsoft_client_id_here"
    client_secret: "your_microsoft_client_secret_here"
    redirect_url: "http://localhost:8000/callback"

# Webhook URLs
webhooks:
  admin: "your_admin_webhook_url_here"
  notifications: "your_notifications_webhook_url_here"

# Flip Detection Settings
flip_settings:
  check_interval: 30  # Seconds between auction checks
  min_profit: 100000  # Minimum profit in coins
  min_profit_percentage: 20  # Minimum profit percentage
  max_price: 1000000000  # Maximum item price to consider
  blacklisted_items: []  # Items to ignore
  whitelist_items: []  # Only check these items if not empty

# Embed Settings
embeds:
  colors:
    success: 0x00ff00  # Green
    error: 0xff0000  # Red
    info: 0x0000ff  # Blue
    flip: 0xffa500  # Orange
  show_timestamps: true
  show_footers: true

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "bot.log"

# Security Settings
security:
  encryption_key: "your_encryption_key_here"  # Will be auto-generated if not provided
  max_login_attempts: 3
  session_timeout: 3600  # Seconds
  require_2fa: true 