services:
  - type: web
    name: flipperbot
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    domains:
      - flipperbot.onrender.com
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: HYPIXEL_API_KEY
        sync: false
      - key: ADMIN_WEBHOOK
        sync: false
      - key: NOTIFICATIONS_WEBHOOK
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_TENANT_ID
        sync: false
      - key: REDIRECT_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: OTP_SECRET_KEY
        sync: false
      - key: ADMIN_CHANNEL_ID
        sync: false 