services:
  - type: web
    name: flipperbot
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18  # Using a more stable Python version
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: HYPIXEL_API_KEY
        sync: false
      - key: ADMIN_WEBHOOK
        sync: false
      - key: NOTIFICATIONS_WEBHOOK
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_TENANT_ID
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: OTP_SECRET_KEY
        sync: false
      - key: ADMIN_CHANNEL_ID
        sync: false
    buildEnv:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
    healthCheckPath: /
    numInstances: 1
    domains:
      - flipperbot.onrender.com 